services:
  - type: web
    name: 2dollarstore-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn wsgi:app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: FRONTEND_URL
        sync: false

  - type: web
    name: 2dollarstore-frontend
    env: node
    buildCommand: |
      cd frontend
      npm install
      npm install -g serve
      npm run build
    startCommand: cd frontend && serve -s build
    envVars:
      - key: REACT_APP_API_URL
        sync: false
    nodeVersion: 18.17.0 