services:
  - type: web
    name: 2dollarstore-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn wsgi:app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: FRONTEND_URL
        sync: false

  - type: web
    name: 2dollarstore-frontend
    env: node
    buildCommand: |
      cd frontend
      rm -rf node_modules package-lock.json
      npm cache clean --force
      npm install --legacy-peer-deps
      npm install -g serve
      npm install @babel/plugin-transform-private-methods @babel/plugin-transform-numeric-separator @babel/plugin-transform-nullish-coalescing-operator @babel/plugin-transform-class-properties @babel/plugin-transform-private-property-in-object @babel/plugin-transform-optional-chaining --save-dev
      npm install nth-check@latest postcss@latest --save-dev
      npm run build
    startCommand: cd frontend && serve -s build
    envVars:
      - key: REACT_APP_API_URL
        sync: false
    nodeVersion: 18.17.0 